# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 01:51

import core.fields
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=50)),
                ('birth_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)])),
                ('birth_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('no_answer', '無回答')], default='no_answer', max_length=9)),
                ('postal_code', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('totp_secret', core.fields.EncryptedTextField(blank=True, null=True)),
                ('totp_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('two_factor_method', models.CharField(choices=[('none', 'なし'), ('email', 'メール'), ('totp', '認証アプリ')], default='none', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member',
                'indexes': [models.Index(fields=['birth_year'], name='idx_member_birth_year')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uq_member_email'), models.CheckConstraint(condition=models.Q(('birth_month__gte', 1), ('birth_month__lte', 12)), name='chk_member_birth_month')],
            },
        ),
    ]
