# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_memberemailcode_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='memberemailcode',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'メール確認'), ('login_2fa', 'ログイン2段階'), ('password_reset', 'パスワード再設定'), ('email_change', 'メールアドレス変更')], max_length=16),
        ),
    ]
