# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_comment'),
        ('scheduling', '0011_program_cast_series_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='members.member')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling.program')),
            ],
            options={
                'db_table': 'member_favorite',
                'indexes': [models.Index(fields=['member', '-created_at'], name='idx_favorite_member')],
                'constraints': [models.UniqueConstraint(fields=('member', 'program'), name='uq_favorite_member_program')],
            },
        ),
    ]
