# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_favorite'),
        ('scheduling', '0011_program_cast_series_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='members.member')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling.program')),
            ],
            options={
                'db_table': 'member_reminder',
                'indexes': [models.Index(fields=['notified_at', 'program'], name='idx_reminder_due')],
                'constraints': [models.UniqueConstraint(fields=('member', 'program'), name='uq_reminder_member_program')],
            },
        ),
    ]
