# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_reminder'),
        ('scheduling', '0011_program_cast_series_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_ms', models.BigIntegerField(default=0)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='members.member')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling.program')),
            ],
            options={
                'db_table': 'member_watch_history',
                'indexes': [models.Index(fields=['member', '-updated_at'], name='idx_watch_member')],
                'constraints': [models.UniqueConstraint(fields=('member', 'program'), name='uq_watch_member_program')],
            },
        ),
    ]
