# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-19 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_channel_short_channel_tint'),
        ('members', '0008_watchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.channel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_favorites', to='members.member')),
            ],
            options={
                'db_table': 'member_channel_favorite',
                'indexes': [models.Index(fields=['member', '-created_at'], name='idx_chanfav_member')],
                'constraints': [models.UniqueConstraint(fields=('member', 'channel'), name='uq_chanfav_member_channel')],
            },
        ),
    ]
