# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_channelfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=128)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member_auth_throttle',
                'indexes': [models.Index(fields=['updated_at'], name='idx_auththrottle_updated')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='uq_auththrottle_scope_key')],
            },
        ),
    ]
