# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auththrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='totp_last_step',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
