# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_totp_last_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('device_label', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='members.member')),
            ],
            options={
                'db_table': 'member_api_token',
                'indexes': [models.Index(fields=['member', 'revoked_at'], name='idx_member_token_mr')],
            },
        ),
        migrations.CreateModel(
            name='MemberLoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('method', models.CharField(max_length=8)),
                ('device_label', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_challenges', to='members.member')),
            ],
            options={
                'db_table': 'member_login_challenge',
                'indexes': [models.Index(fields=['member'], name='idx_member_challenge_m')],
            },
        ),
    ]
