# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_memberapitoken_memberloginchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='JP', max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
