# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medialib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rtmp_app', models.CharField(max_length=200)),
                ('rtmp_key', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'live_source',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('cf_live_input_id', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_stream_key', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_livestream_id', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_ingest_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_filler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.fillerplaylist')),
            ],
            options={
                'db_table': 'channel',
            },
        ),
    ]
