# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-12 00:24

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='agent_token',
            field=core.fields.EncryptedTextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='youtube_stream_key',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
