# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-13 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_channel_cf_playback_hls_url'),
        ('medialib', '0006_asset_normalize_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slate_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.asset'),
        ),
    ]
