# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-14 07:27

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_channel_slate_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesource',
            name='srt_latency_ms',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='livesource',
            name='srt_passphrase',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
