# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_livesource_srt_latency_ms_livesource_srt_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='short',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='tint',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
