# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_channel_short_channel_tint'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='clock_overlay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='clock_windows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
