# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-25 03:00

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_channel_clock_overlay_enabled_channel_clock_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='youtube_ingest_url_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_livestream_id_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_stream_key_2',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
