# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_channel_youtube_ingest_url_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChimeSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('r2_key', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chime_sound',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelChime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('eew', 'EEW (緊急)'), ('weather', '気象'), ('general', 'その他')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chimes', to='core.channel')),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chimesound')),
            ],
            options={
                'db_table': 'channel_chime',
                'constraints': [models.UniqueConstraint(fields=('channel', 'category'), name='uniq_channel_chime_category')],
            },
        ),
    ]
