# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_clockstylepreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='broadcast_windows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
