# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_channel_broadcast_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelchime',
            name='category',
            field=models.CharField(choices=[('eew', 'EEW (緊急)'), ('weather', '気象'), ('general', 'その他'), ('cm_in', 'CM入り')], max_length=16),
        ),
    ]
