# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-09 02:22

import django.contrib.postgres.constraints
import django.db.models.deletion
import scheduling.models
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('medialib', '0001_initial'),
    ]

    operations = [
        # program の EXCLUDE 制約 (channel = , tstzrange && ) は gist で channel 等価比較を
        # 行うため btree_gist が必要。同一マイグレーション内で制約追加より前に有効化する。
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recorded', '録画'), ('live', '生')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('public_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.asset')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='core.channel')),
                ('cm_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.cmbundle')),
                ('live_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.livesource')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='AdBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_ms', models.BigIntegerField()),
                ('grid', models.CharField(choices=[('15s', '15秒'), ('20s', '20秒')], max_length=8)),
                ('duration_ms', models.BigIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_breaks', to='scheduling.program')),
            ],
            options={
                'db_table': 'ad_break',
            },
        ),
        migrations.CreateModel(
            name='AdBreakItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('ad_break', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scheduling.adbreak')),
                ('cm_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.cmcreative')),
            ],
            options={
                'db_table': 'ad_break_item',
                'ordering': ['ad_break', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('ad_break', 'seq'), name='uq_ad_break_item_seq')],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['channel', 'start_at'], name='idx_program_ch_time'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='chk_program_time'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('live_source__isnull', True), ('type', 'recorded')), models.Q(('asset__isnull', True), ('live_source__isnull', False), ('type', 'live')), _connector='OR'), name='chk_program_source'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('channel'), '='), (scheduling.models.TsTzRange(models.F('start_at'), models.F('end_at')), '&&')], name='program_no_overlap_per_channel'),
        ),
    ]
