# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
        ('medialib', '0003_backfill_screening_approved'),
        ('scheduling', '0003_series_program_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('duration_ms', models.BigIntegerField()),
                ('program_type', models.CharField(choices=[('recorded', '録画'), ('live', '生')], max_length=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('default_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.asset')),
                ('live_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.livesource')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.series')),
            ],
            options={
                'db_table': 'series_slot',
                'constraints': [models.CheckConstraint(condition=models.Q(('dow__gte', 0), ('dow__lte', 6)), name='chk_slot_dow'), models.CheckConstraint(condition=models.Q(models.Q(('default_asset__isnull', False), ('program_type', 'recorded')), models.Q(('live_source__isnull', False), ('program_type', 'live')), _connector='OR'), name='chk_slot_source')],
            },
        ),
    ]
