# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_seriesslot_recurrence_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
