# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_channel_slate_asset'),
        ('scheduling', '0006_series_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=8, null=True)),
                ('layer', models.IntegerField()),
                ('kind', models.CharField(choices=[('graphic', '画像/動画+文字'), ('video', '透過動画'), ('text', '文字')], default='graphic', max_length=8)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('template', models.CharField(blank=True, max_length=64)),
                ('show_at_ms', models.BigIntegerField(default=0)),
                ('hide_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('seq', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_cues', to='core.channel')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_cues', to='scheduling.program')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_cues', to='scheduling.series')),
            ],
            options={
                'db_table': 'graphic_cue',
                'ordering': ['seq', 'id'],
            },
        ),
    ]
