# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-14 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0006_asset_normalize_started_at'),
        ('scheduling', '0007_graphiccue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_no', models.IntegerField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('planned', '予定'), ('confirmed', '確定'), ('aired', '放送済')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.asset')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='scheduling.series')),
            ],
            options={
                'db_table': 'episode',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='scheduling.episode'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['series', 'air_date'], name='idx_episode_series_date'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(condition=models.Q(('episode_no__isnull', False)), fields=('series', 'episode_no'), name='uq_episode_series_no'),
        ),
    ]
