# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_episode_program_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='genre',
            field=models.CharField(blank=True, choices=[('ニュース', 'ニュース'), ('情報', '情報'), ('アニメ', 'アニメ'), ('映画', '映画'), ('音楽', '音楽'), ('ゲーム', 'ゲーム'), ('バラエティ', 'バラエティ'), ('教養', '教養'), ('文化', '文化'), ('科学', '科学'), ('技術', '技術'), ('語学', '語学'), ('ドキュメンタリー', 'ドキュメンタリー')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.CharField(blank=True, choices=[('ニュース', 'ニュース'), ('情報', '情報'), ('アニメ', 'アニメ'), ('映画', '映画'), ('音楽', '音楽'), ('ゲーム', 'ゲーム'), ('バラエティ', 'バラエティ'), ('教養', '教養'), ('文化', '文化'), ('科学', '科学'), ('技術', '技術'), ('語学', '語学'), ('ドキュメンタリー', 'ドキュメンタリー')], default='', max_length=20),
        ),
    ]
