# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_program_genre_series_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='vod_available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='vod_visibility',
            field=models.CharField(choices=[('off', '公開しない'), ('public', '全員'), ('members', '会員限定'), ('subscribers', 'サブスク限定')], default='off', max_length=12),
        ),
    ]
