# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_program_vod_available_until_program_vod_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
    ]
