# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_program_cast_series_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
