# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0012_program_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[("pg12", "PG12"), ("r15", "R15+"), ("r18", "R18+")],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[("pg12", "PG12"), ("r15", "R15+"), ("r18", "R18+")],
                default="",
                max_length=8,
            ),
        ),
    ]
