# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_program_rating_series_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesslot',
            name='recurrence_kind',
            field=models.CharField(choices=[('weekly', '毎週(曜日)'), ('monthly_nth_dow', '第N曜'), ('days_of_month', '毎月の指定日'), ('days_ending', '末尾が指定の日'), ('daily', '毎日')], default='weekly', max_length=20),
        ),
    ]
