# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_weatheringest'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='clock_hidden',
            field=models.BooleanField(default=False, verbose_name='朝・夕の時計を表示しない'),
        ),
        migrations.AddField(
            model_name='series',
            name='clock_hidden',
            field=models.BooleanField(default=False, verbose_name='朝・夕の時計を表示しない'),
        ),
    ]
