# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_program_clock_hidden_series_clock_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uri', models.CharField(max_length=500, unique=True)),
                ('account_acct', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(max_length=24)),
                ('emergency', models.BooleanField(default=False)),
                ('max_intensity', models.CharField(blank=True, max_length=4)),
                ('max_intensity_rank', models.FloatField(blank=True, null=True)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('epicenter', models.CharField(blank=True, max_length=120)),
                ('telop', models.TextField(blank=True)),
                ('aired', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'earthquake_alert',
                'indexes': [models.Index(fields=['created_at'], name='idx_eqalert_created'), models.Index(fields=['aired'], name='idx_eqalert_aired')],
            },
        ),
    ]
