# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_program_series_youtube_dedicated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarthquakeAlert',
        ),
    ]
