# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_delete_earthquakealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('article', '記事・お知らせ'), ('campaign', 'キャンペーン応募')], default='article', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, help_text='本文(テキスト)。HTML可。')),
                ('media_url', models.CharField(blank=True, help_text='画像/動画 URL (外部または R2)', max_length=500)),
                ('form_url', models.CharField(blank=True, help_text='応募フォーム URL (kind=campaign 時)', max_length=500)),
                ('campaign_start', models.DateTimeField(blank=True, help_text='応募受付開始', null=True)),
                ('campaign_end', models.DateTimeField(blank=True, help_text='応募受付終了', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduling.series')),
            ],
            options={
                'db_table': 'series_post',
                'ordering': ['-published_at'],
            },
        ),
    ]
