# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chimesound_channelchime'),
        ('members', '0009_channelfavorite'),
        ('scheduling', '0020_seriespost'),
        ('youtube', '0009_programbroadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('message', '投書・メッセージ'), ('campaign', 'キャンペーン応募')], default='message', max_length=20)),
                ('title', models.CharField(help_text='例: "番組へメッセージを送る"', max_length=300)),
                ('description', models.TextField(blank=True, help_text='フォーム上部の説明文。')),
                ('enabled', models.BooleanField(default=False, help_text='公開ページへの表示 ON/OFF。')),
                ('requires_login', models.BooleanField(default=False, help_text='True=会員ログイン必須 (campaign の場合は True を推奨)。')),
                ('fields', models.JSONField(default=list, help_text='フィールド定義リスト。')),
                ('success_message', models.TextField(blank=True, default='送信しました。ありがとうございました。', help_text='送信完了メッセージ。')),
                ('notify_email', models.CharField(blank=True, help_text='新着投稿をここへメール通知 (空=通知なし)。複数は半角カンマ区切り。', max_length=200)),
                ('starts_at', models.DateTimeField(blank=True, help_text='応募受付開始 (campaign)。', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='応募受付終了 (campaign)。', null=True)),
                ('prize', models.TextField(blank=True, help_text='賞品・特典の説明 (campaign)。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audience_form',
                'ordering': ['kind', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AudienceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('submitter_name', models.CharField(blank=True, max_length=200)),
                ('submitter_email', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', '未読'), ('read', '既読'), ('handled', '対応済')], default='new', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audience_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='series',
            name='x_handle',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='series',
            name='x_hashtag',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__gt', '')), fields=('channel', 'slug'), name='uniq_series_slug_per_channel'),
        ),
        migrations.AddField(
            model_name='audienceform',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_forms', to='scheduling.series'),
        ),
        migrations.AddField(
            model_name='audiencesubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='scheduling.audienceform'),
        ),
        migrations.AddField(
            model_name='audiencesubmission',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_submissions', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='audiencesubmission',
            index=models.Index(fields=['form', 'status'], name='idx_audience_sub_form_status'),
        ),
        migrations.AddIndex(
            model_name='audiencesubmission',
            index=models.Index(fields=['created_at'], name='idx_audience_sub_created'),
        ),
    ]
