# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-02 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_channel_broadcast_windows'),
        ('medialib', '0009_asset_rerun_eligible'),
        ('scheduling', '0023_clock_style_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='record_live',
            field=models.BooleanField(default=False, verbose_name='この放送を自動録画する'),
        ),
        migrations.AddField(
            model_name='program',
            name='recording_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.asset'),
        ),
        migrations.CreateModel(
            name='LiveRecordingIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=500, unique=True)),
                ('state', models.CharField(choices=[('normalizing', '正規化中'), ('bound', '番組に紐付け済'), ('no_program', '対象番組なし'), ('failed', '失敗')], default='normalizing', max_length=12)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.asset')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.channel')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.program')),
            ],
            options={
                'db_table': 'live_recording_ingest',
                'indexes': [models.Index(fields=['state'], name='idx_live_rec_ingest_state')],
            },
        ),
    ]
