# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0010_asset_captions'),
        ('playout', '0007_alter_playoutevent_action'),
        ('scheduling', '0024_program_record_live_program_recording_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRundown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_rundown', to='scheduling.program')),
            ],
            options={
                'db_table': 'live_rundown',
            },
        ),
        migrations.CreateModel(
            name='LiveCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('kind', models.CharField(choices=[('section', '本編'), ('cm', 'CM'), ('vt', 'VT')], max_length=8)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('planned_duration_ms', models.BigIntegerField()),
                ('grid', models.CharField(blank=True, choices=[('15s', '15秒'), ('20s', '20秒')], max_length=8, null=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('firing', 'firing'), ('aired', 'aired'), ('skipped', 'skipped')], default='pending', max_length=8)),
                ('auto_fire', models.BooleanField(default=False)),
                ('auto_offset_ms', models.BigIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.asset')),
                ('cm_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.cmbundle')),
                ('fired_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='playout.playoutevent')),
                ('rundown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='scheduling.liverundown')),
            ],
            options={
                'db_table': 'live_cue',
                'ordering': ['rundown', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('rundown', 'seq'), name='uq_live_cue_seq')],
            },
        ),
    ]
