# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0010_asset_captions'),
        ('scheduling', '0025_liverundown_livecue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRundownTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rundown_template', to='scheduling.seriesslot')),
            ],
            options={
                'db_table': 'live_rundown_template',
            },
        ),
        migrations.CreateModel(
            name='LiveRundownTemplateCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('kind', models.CharField(choices=[('section', '本編'), ('cm', 'CM'), ('vt', 'VT')], max_length=8)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('planned_duration_ms', models.BigIntegerField()),
                ('grid', models.CharField(blank=True, choices=[('15s', '15秒'), ('20s', '20秒')], max_length=8, null=True)),
                ('auto_fire', models.BooleanField(default=False)),
                ('auto_offset_ms', models.BigIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.asset')),
                ('cm_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.cmbundle')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='scheduling.liverundowntemplate')),
            ],
            options={
                'db_table': 'live_rundown_template_cue',
                'ordering': ['template', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('template', 'seq'), name='uq_tmpl_cue_seq')],
            },
        ),
    ]
