# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0026_liverundowntemplate_liverundowntemplatecue'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecue',
            name='auto_anchor',
            field=models.CharField(choices=[('start', '開始相対'), ('wallclock', '壁時計')], default='start', max_length=10),
        ),
        migrations.AddField(
            model_name='livecue',
            name='auto_wall_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liverundowntemplatecue',
            name='auto_anchor',
            field=models.CharField(choices=[('start', '開始相対'), ('wallclock', '壁時計')], default='start', max_length=10),
        ),
        migrations.AddField(
            model_name='liverundowntemplatecue',
            name='auto_wall_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
