# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0010_asset_captions'),
        ('scheduling', '0027_livecue_auto_anchor_livecue_auto_wall_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidecastIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=500, unique=True)),
                ('slug', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('normalizing', '正規化中'), ('ready', '取り込み完了'), ('failed', '失敗')], default='normalizing', max_length=12)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.asset')),
            ],
            options={
                'db_table': 'slidecast_ingest',
                'indexes': [models.Index(fields=['state'], name='idx_slidecast_ingest_state')],
            },
        ),
    ]
