# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_channelchime_category'),
        ('medialib', '0011_asset_offload'),
        ('scheduling', '0029_rankingingest'),
        ('youtube', '0011_youtubedescriptiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='fc_required_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seriespost',
            name='fc_required_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='vod_visibility',
            field=models.CharField(choices=[('off', '公開しない'), ('public', '全員'), ('members', '会員限定'), ('subscribers', 'サブスク限定'), ('fanclub', 'ファンクラブ限定')], default='off', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fc_required_level__isnull', False), ('vod_visibility', 'fanclub')), models.Q(('vod_visibility', 'fanclub'), _negated=True), _connector='OR'), name='chk_program_fc_requires_level'),
        ),
    ]
