# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_program_fc_required_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='exposure_policy',
            field=models.CharField(blank=True, choices=[('public', '全公開'), ('site_public', 'サイト限定・公開'), ('site_members', 'サイト会員限定'), ('members_yt_site', '会員限定(YT+サイト)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='exposure_policy_default',
            field=models.CharField(choices=[('public', '全公開'), ('site_public', 'サイト限定・公開'), ('site_members', 'サイト会員限定'), ('members_yt_site', '会員限定(YT+サイト)')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='seriesslot',
            name='exposure_policy',
            field=models.CharField(blank=True, choices=[('public', '全公開'), ('site_public', 'サイト限定・公開'), ('site_members', 'サイト会員限定'), ('members_yt_site', '会員限定(YT+サイト)')], default='', max_length=20),
        ),
    ]
