# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-09-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0031_program_exposure_policy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankingIngest',
        ),
        migrations.DeleteModel(
            name='SlidecastIngest',
        ),
        migrations.DeleteModel(
            name='WeatherIngest',
        ),
    ]
