# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-19 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_channel_short_channel_tint'),
        ('scheduling', '0011_program_cast_series_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='scheduling.program')),
            ],
            options={
                'db_table': 'program_view',
                'indexes': [models.Index(fields=['program'], name='idx_progview_program')],
                'constraints': [models.UniqueConstraint(fields=('program', 'viewer_id'), name='uq_progview_prog_viewer')],
            },
        ),
        migrations.CreateModel(
            name='ViewerPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(max_length=64)),
                ('last_seen', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.channel')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.program')),
            ],
            options={
                'db_table': 'viewer_presence',
                'indexes': [models.Index(fields=['channel', 'last_seen'], name='idx_presence_ch_seen')],
                'constraints': [models.UniqueConstraint(fields=('viewer_id', 'channel'), name='uq_presence_viewer_ch')],
            },
        ),
    ]
