# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=100)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=512)),
                ('status', models.PositiveSmallIntegerField()),
                ('is_page', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'access_log_entry',
                'indexes': [models.Index(fields=['host', 'created_at'], name='idx_accesslog_host_created')],
            },
        ),
    ]
