# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('program', '番組'), ('cm', 'CM'), ('filler', 'フィラー'), ('bumper', 'バンパー'), ('slate', 'スレート')], max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('r2_key', models.CharField(blank=True, max_length=500, null=True)),
                ('source_path', models.CharField(blank=True, max_length=500, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('fps', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('vcodec', models.CharField(blank=True, max_length=64, null=True)),
                ('acodec', models.CharField(blank=True, max_length=64, null=True)),
                ('normalize_status', models.CharField(choices=[('pending', '待機'), ('processing', '正規化中'), ('ready', '送出可'), ('failed', '失敗')], default='pending', max_length=16)),
                ('normalize_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='CmBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cm_bundle',
            },
        ),
        migrations.CreateModel(
            name='CmBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
            ],
            options={
                'db_table': 'cm_bundle_item',
                'ordering': ['cm_bundle', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='FillerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
            ],
            options={
                'db_table': 'filler_item',
                'ordering': ['filler_playlist', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='FillerPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'filler_playlist',
            },
        ),
        migrations.CreateModel(
            name='CmCreative',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cm', serialize=False, to='medialib.asset')),
                ('advertiser', models.CharField(max_length=200)),
                ('grid', models.CharField(choices=[('15s', '15秒'), ('20s', '20秒')], max_length=8)),
                ('campaign_start', models.DateField(blank=True, null=True)),
                ('campaign_end', models.DateField(blank=True, null=True)),
                ('max_airings', models.IntegerField(blank=True, null=True)),
                ('aired_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cm_creative',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(condition=models.Q(('normalize_status', 'ready')), fields=['kind'], name='idx_asset_kind_ready'),
        ),
        migrations.AddField(
            model_name='cmbundleitem',
            name='cm_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medialib.cmbundle'),
        ),
        migrations.AddField(
            model_name='filleritem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.asset'),
        ),
        migrations.AddField(
            model_name='filleritem',
            name='filler_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medialib.fillerplaylist'),
        ),
        migrations.AddField(
            model_name='cmbundleitem',
            name='cm_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialib.cmcreative'),
        ),
        migrations.AddConstraint(
            model_name='filleritem',
            constraint=models.UniqueConstraint(fields=('filler_playlist', 'seq'), name='uq_filler_item_seq'),
        ),
        migrations.AddConstraint(
            model_name='cmbundleitem',
            constraint=models.UniqueConstraint(fields=('cm_bundle', 'seq'), name='uq_cm_bundle_item_seq'),
        ),
    ]
