# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmcreative',
            name='screening_status',
            field=models.CharField(choices=[('pending', '未考査'), ('approved', '考査OK'), ('rejected', '考査NG')], default='pending', max_length=10),
        ),
    ]
