# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0003_backfill_screening_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CueSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cue_sheet', to='medialib.asset')),
            ],
            options={
                'db_table': 'cue_sheet',
            },
        ),
        migrations.CreateModel(
            name='CuePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('kind', models.CharField(choices=[('content', '本編'), ('ad_break', 'CM枠')], max_length=16)),
                ('duration_ms', models.BigIntegerField()),
                ('grid', models.CharField(blank=True, choices=[('15s', '15秒'), ('20s', '20秒')], max_length=8, null=True)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('cue_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='medialib.cuesheet')),
            ],
            options={
                'db_table': 'cue_point',
                'ordering': ['cue_sheet', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('cue_sheet', 'seq'), name='uq_cue_point_seq')],
            },
        ),
    ]
