# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0006_asset_normalize_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='passthrough',
            field=models.BooleanField(default=False),
        ),
    ]
