# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-09-11 14:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialib", "0011_asset_offload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "署名待ち"),
                            ("uploading", "アップロード中"),
                            ("verifying", "検証中"),
                            ("completed", "完了"),
                            ("aborted", "中断"),
                            ("expired", "期限切れ"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("program", "番組"),
                            ("cm", "CM"),
                            ("filler", "フィラー"),
                            ("bumper", "バンパー"),
                            ("slate", "スレート"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("expected_size_bytes", models.BigIntegerField()),
                ("expected_sha256", models.CharField(max_length=64)),
                ("observed_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("verified_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("staging_key", models.CharField(max_length=500, unique=True)),
                (
                    "canonical_key",
                    models.CharField(blank=True, max_length=500, null=True, unique=True),
                ),
                ("multipart_upload_id", models.CharField(blank=True, max_length=512, null=True)),
                ("object_etag_or_version", models.CharField(blank=True, max_length=512, null=True)),
                ("idempotency_key_hash", models.CharField(max_length=64)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("verify_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("aborted_at", models.DateTimeField(blank=True, null=True)),
                ("cleanup_after", models.DateTimeField(blank=True, null=True)),
                ("object_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cleanup_attempts", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_session",
                        to="medialib.asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "asset_upload",
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="idx_upload_status_expiry"),
                    models.Index(
                        fields=["status", "cleanup_after"], name="idx_upload_status_cleanup"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "idempotency_key_hash"), name="uq_asset_upload_owner_idem"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "completed"), _negated=True),
                            models.Q(
                                ("asset__isnull", False),
                                ("canonical_key__isnull", False),
                                ("observed_size_bytes__isnull", False),
                                ("verified_sha256__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_upload_completed_fields",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "completed"), ("asset__isnull", True), _connector="OR"
                        ),
                        name="ck_upload_asset_only_complete",
                    ),
                ],
            },
        ),
    ]
