# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-09-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialib", "0012_assetupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetupload",
            name="last_progress_part_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
