# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-25 08:37

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0011_member_totp_last_step'),
        ('scheduling', '0029_rankingingest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', '有効'), ('suspended', '停止中')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'creator',
            },
        ),
        migrations.CreateModel(
            name='CreatorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='fanclub.creator')),
            ],
            options={
                'db_table': 'creator_invitation',
            },
        ),
        migrations.CreateModel(
            name='CreatorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price_jpy', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='fanclub.creator')),
            ],
            options={
                'db_table': 'creator_tier',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CreatorMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '在籍中'), ('left', '退会済')], default='active', max_length=6)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fanclub.creator')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanclub_memberships', to='members.member')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='fanclub.creatortier')),
            ],
            options={
                'db_table': 'creator_membership',
            },
        ),
        migrations.CreateModel(
            name='SlotContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('monthly_fee_jpy', models.PositiveIntegerField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('suspended', 'suspended'), ('ended', 'ended')], default='draft', max_length=9)),
                ('youtube_destination', models.CharField(choices=[('operator_channel', '運営チャンネル'), ('creator_channel', 'クリエイター自チャンネル'), ('none', '配信連携なし')], default='none', max_length=17)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_contracts', to='fanclub.creator')),
            ],
            options={
                'db_table': 'slot_contract',
            },
        ),
        migrations.CreateModel(
            name='CreatorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('google_sub', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fanclub.creator')),
            ],
            options={
                'db_table': 'creator_account',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('creator'), name='uq_creator_account_creator_email'), models.UniqueConstraint(condition=models.Q(('google_sub__gt', '')), fields=('google_sub',), name='uq_creator_account_google_sub')],
            },
        ),
        migrations.CreateModel(
            name='CreatorSeriesLink',
            fields=[
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fanclub_link', serialize=False, to='scheduling.series')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_links', to='fanclub.creator')),
            ],
            options={
                'db_table': 'creator_series_link',
                'indexes': [models.Index(fields=['creator'], name='idx_fc_series_link_creator')],
            },
        ),
        migrations.AddConstraint(
            model_name='creatortier',
            constraint=models.UniqueConstraint(fields=('creator', 'level'), name='uq_creator_tier_creator_level'),
        ),
        migrations.AddConstraint(
            model_name='creatortier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 0), ('price_jpy__isnull', True)), ('level__gt', 0), _connector='OR'), name='chk_creator_tier_free_level_no_price'),
        ),
        migrations.AddIndex(
            model_name='creatormembership',
            index=models.Index(fields=['creator', 'status'], name='idx_fc_membership_cr_status'),
        ),
        migrations.AddConstraint(
            model_name='creatormembership',
            constraint=models.UniqueConstraint(fields=('member', 'creator'), name='uq_creator_membership_member_creator'),
        ),
        migrations.AddIndex(
            model_name='slotcontract',
            index=models.Index(fields=['creator', 'status'], name='idx_slot_contract_cr_status'),
        ),
    ]
