# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='creator',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='creator',
            name='hide_contact_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='invoice_registration_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='creator',
            name='is_individual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='creator',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', '審査待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='creator',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='creator',
            name='representative_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
