# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creator',
            name='stripe_connect_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatormembership',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatormembership',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatormembership',
            name='last_event_created',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatormembership',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creatormembership',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creatortier',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
