# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0002_creator_address_creator_contact_email_and_more'),
        ('fanclub', '0003_fcprocessedstripeevent'),
    ]

    operations = [
    ]
