# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0003_fcprocessedstripeevent'),
        ('members', '0012_memberapitoken_memberloginchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=100)),
                ('gross_amount_jpy', models.PositiveIntegerField()),
                ('application_fee_jpy', models.PositiveIntegerField()),
                ('net_amount_jpy', models.PositiveIntegerField()),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('disputed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='fanclub.creator')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fanclub.creatortier')),
            ],
            options={
                'db_table': 'fanclub_settlement',
                'indexes': [models.Index(fields=['creator', 'created_at'], name='idx_fc_settlement_cr_created')],
            },
        ),
    ]
