# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0004_fcsettlement'),
        ('fanclub', '0004_merge_20260727_1943'),
    ]

    operations = [
    ]
