# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0004_merge_20260727_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotcontract',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slotcontract',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotcontract',
            name='last_event_created',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotcontract',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='slotcontract',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
