# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 23:52

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_channel_members_filler_channel_site_only_filler'),
        ('fanclub', '0004_merge_20260727_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='youtube_destination_ingest_url',
            field=models.CharField(blank=True, default='rtmp://a.rtmp.youtube.com/live2', max_length=300),
        ),
        migrations.AddField(
            model_name='creator',
            name='youtube_destination_stream_key',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreatorYoutubeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_output_uid', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.channel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_outputs', to='fanclub.creator')),
            ],
            options={
                'db_table': 'creator_youtube_output',
                'constraints': [models.UniqueConstraint(fields=('creator', 'channel'), name='uq_creator_youtube_output')],
            },
        ),
    ]
