# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0005_merge_0004_fcsettlement_0004_merge_20260727_1943'),
        ('fanclub', '0005_slotcontract_cancel_at_period_end_and_more'),
    ]

    operations = [
    ]
