# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0005_creator_youtube_destination_ingest_url_and_more'),
        ('fanclub', '0006_merge_20260728_1203'),
    ]

    operations = [
    ]
