# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-08-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0007_merge_20260728_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatormembership',
            name='pending_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fanclub.creatortier'),
        ),
        migrations.AddField(
            model_name='creatormembership',
            name='pending_tier_effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
