# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-08-10 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0009_creatormembership_member_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='creator',
            name='cover_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='creator',
            name='sns_instagram_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='creator',
            name='sns_x_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='creator',
            name='sns_youtube_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='creator',
            name='theme_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', '「#38bdf8」形式で指定してください')]),
        ),
        migrations.AddField(
            model_name='creator',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
