# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-08-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0010_creator_avatar_url_creator_cover_url_and_more'),
        ('members', '0012_memberapitoken_memberloginchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_jpy', models.PositiveIntegerField()),
                ('application_fee_jpy', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', '決済待ち'), ('paid', '支払済')], default='pending', max_length=8)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tips', to='fanclub.creator')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
            ],
            options={
                'db_table': 'fanclub_tip',
                'indexes': [models.Index(fields=['creator', 'status', 'created_at'], name='idx_fc_tip_cr_status')],
            },
        ),
    ]
