# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-08-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0011_fctip'),
        ('members', '0012_memberapitoken_memberloginchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatormembership',
            name='gift_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FcGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField()),
                ('amount_jpy', models.PositiveIntegerField()),
                ('application_fee_jpy', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', '決済待ち'), ('paid', '支払済(未償還)'), ('redeemed', '償還済')], default='pending', max_length=8)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=100)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts', to='fanclub.creator')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_fc_gifts', to='members.member')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fanclub.creatortier')),
            ],
            options={
                'db_table': 'fanclub_gift',
                'indexes': [models.Index(fields=['creator', 'status'], name='idx_fc_gift_cr_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='uq_fc_gift_code')],
            },
        ),
    ]
