# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-08-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0012_creatormembership_gift_expires_at_fcgift'),
        ('members', '0012_memberapitoken_memberloginchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='chat_required_level',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='FcChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='fanclub.creator')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.member')),
            ],
            options={
                'db_table': 'fanclub_chat_message',
                'indexes': [models.Index(fields=['creator', '-created_at'], name='idx_fc_chat_cr_created')],
            },
        ),
    ]
