# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0013_creator_chat_required_level_fcchatmessage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creatortier',
            name='chk_creator_tier_free_level_no_price',
        ),
        migrations.RenameField(
            model_name='creatortier',
            old_name='price_jpy',
            new_name='price_minor',
        ),
        migrations.RenameField(
            model_name='fcgift',
            old_name='amount_jpy',
            new_name='amount_minor',
        ),
        migrations.RenameField(
            model_name='fcgift',
            old_name='application_fee_jpy',
            new_name='application_fee_minor',
        ),
        migrations.RenameField(
            model_name='fcsettlement',
            old_name='application_fee_jpy',
            new_name='application_fee_minor',
        ),
        migrations.RenameField(
            model_name='fcsettlement',
            old_name='gross_amount_jpy',
            new_name='gross_amount_minor',
        ),
        migrations.RenameField(
            model_name='fcsettlement',
            old_name='net_amount_jpy',
            new_name='net_amount_minor',
        ),
        migrations.RenameField(
            model_name='fctip',
            old_name='amount_jpy',
            new_name='amount_minor',
        ),
        migrations.RenameField(
            model_name='fctip',
            old_name='application_fee_jpy',
            new_name='application_fee_minor',
        ),
        migrations.RenameField(
            model_name='slotcontract',
            old_name='monthly_fee_jpy',
            new_name='monthly_fee_minor',
        ),
        migrations.AddField(
            model_name='creatortier',
            name='currency',
            field=models.CharField(default='jpy', max_length=3),
        ),
        migrations.AddField(
            model_name='fcgift',
            name='currency',
            field=models.CharField(default='jpy', max_length=3),
        ),
        migrations.AddField(
            model_name='fcsettlement',
            name='currency',
            field=models.CharField(default='jpy', max_length=3),
        ),
        migrations.AddField(
            model_name='fctip',
            name='currency',
            field=models.CharField(default='jpy', max_length=3),
        ),
        migrations.AddField(
            model_name='slotcontract',
            name='currency',
            field=models.CharField(default='jpy', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='creatortier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 0), ('price_minor__isnull', True)), ('level__gt', 0), _connector='OR'), name='chk_creator_tier_free_level_no_price'),
        ),
    ]
