# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-09-14 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fanclub", "0014_remove_creatortier_chk_creator_tier_free_level_no_price_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FcTip",
        ),
        migrations.DeleteModel(
            name="FcGift",
        ),
    ]
