# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-09-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0015_delete_fcgift_fctip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcPendingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fanclub_pending_invoice',
                'indexes': [models.Index(fields=['stripe_subscription_id'], name='idx_fc_pending_sub'), models.Index(fields=['stripe_customer_id'], name='idx_fc_pending_cus'), models.Index(fields=['created_at'], name='idx_fc_pending_created')],
            },
        ),
    ]
