# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.17 on 2026-09-22 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0016_fc_pending_invoice'),
        ('members', '0013_member_country_alter_member_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorAddonGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=50)),
                ('external_reference', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_grants', to='fanclub.creator')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.member')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fanclub.creatortier')),
            ],
            options={
                'db_table': 'fanclub_creator_addon_grant',
                'indexes': [models.Index(fields=['creator', 'member', 'expires_at'], name='idx_fc_addon_grant_cme')],
                'constraints': [models.UniqueConstraint(fields=('addon_name', 'external_reference'), name='uq_fc_addon_grant_ref')],
            },
        ),
    ]
