# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('medialib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeCredential',
            fields=[
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='youtube_credential', serialize=False, to='core.channel')),
                ('client_id', models.CharField(max_length=300)),
                ('client_secret', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('scopes', models.CharField(default='https://www.googleapis.com/auth/youtube.force-ssl', max_length=300)),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'youtube_credential',
            },
        ),
        migrations.CreateModel(
            name='YoutubeConfig',
            fields=[
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='youtube_config', serialize=False, to='core.channel')),
                ('title_template', models.CharField(default='ICS-TV {date} {start}-{end}', max_length=300)),
                ('privacy', models.CharField(choices=[('public', 'public'), ('unlisted', 'unlisted'), ('private', 'private')], default='public', max_length=12)),
                ('enable_monitor', models.BooleanField(default=False)),
                ('rolling_hours', models.IntegerField(default=24)),
                ('slot_minutes', models.IntegerField(default=120)),
                ('default_thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.asset')),
            ],
            options={
                'db_table': 'youtube_config',
            },
        ),
        migrations.CreateModel(
            name='YoutubeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('broadcast_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('ready', 'ready'), ('testing', 'testing'), ('live', 'live'), ('complete', 'complete'), ('error', 'error')], default='created', max_length=12)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_slots', to='core.channel')),
            ],
            options={
                'db_table': 'youtube_slot',
                'ordering': ['channel', 'window_start'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'window_start'), name='uq_youtube_slot_window')],
            },
        ),
    ]
