# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-12 00:24

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubecredential',
            name='client_secret',
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='youtubecredential',
            name='refresh_token',
            field=core.fields.EncryptedTextField(),
        ),
    ]
