# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_youtubecredential_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeslot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubeslot',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
