# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_youtubeslot_description_youtubeslot_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeconfig',
            name='description_template',
            field=models.TextField(blank=True, default='ICS-TV {date} {start}-{end} (JST) の配信枠です。\n\n{programs}'),
        ),
    ]
