# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_youtubeconfig_description_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeconfig',
            name='nudge_lead_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='youtubeconfig',
            name='nudge_template',
            field=models.TextField(default='まもなくこの配信は終了します。続きは次の配信でご覧ください ▶ {url}'),
        ),
        migrations.AddField(
            model_name='youtubeslot',
            name='next_nudged',
            field=models.BooleanField(default=False),
        ),
    ]
