# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_youtubeconfig_nudge_lead_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeconfig',
            name='nudge_ended_template',
            field=models.TextField(default='この配信は終了しています。続きは次の配信でご覧ください ▶ {url}'),
        ),
        migrations.AddField(
            model_name='youtubeslot',
            name='ended_nudged',
            field=models.BooleanField(default=False),
        ),
    ]
