# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_youtubeconfig_nudge_ended_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeconfig',
            name='title_template',
            field=models.CharField(default='{channel} {date} {start}-{end}', max_length=300),
        ),
    ]
