# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-25 02:47

import django.db.models.deletion
import youtube.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_channel_clock_overlay_enabled_channel_clock_windows'),
        ('medialib', '0009_asset_rerun_eligible'),
        ('youtube', '0007_alter_youtubeconfig_title_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeBroadcastPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_template', models.CharField(blank=True, default='', max_length=300)),
                ('description_template', models.TextField(blank=True, default='')),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('privacy', models.CharField(choices=[('public', 'public'), ('unlisted', 'unlisted'), ('private', 'private')], default='public', max_length=12)),
                ('made_for_kids', models.BooleanField(default=False)),
                ('default_language', models.CharField(blank=True, default='', max_length=10)),
                ('default_audio_language', models.CharField(blank=True, default='', max_length=10)),
                ('latency', models.CharField(choices=[('normal', 'normal'), ('low', 'low'), ('ultraLow', 'ultraLow')], default='low', max_length=10)),
                ('enable_dvr', models.BooleanField(default=True)),
                ('enable_embed', models.BooleanField(default=True)),
                ('enable_auto_start', models.BooleanField(default=False)),
                ('enable_auto_stop', models.BooleanField(default=False)),
                ('record_from_start', models.BooleanField(default=True)),
                ('license', models.CharField(choices=[('youtube', '標準の YouTube ライセンス'), ('creativeCommon', 'クリエイティブ・コモンズ')], default='youtube', max_length=16)),
                ('public_stats_viewable', models.BooleanField(default=True)),
                ('playlist_id', models.CharField(blank=True, default='', max_length=64)),
                ('manual_checklist', models.JSONField(blank=True, default=youtube.models.default_manual_checklist)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_presets', to='core.channel')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.asset')),
            ],
            options={
                'db_table': 'youtube_broadcast_preset',
                'ordering': ['channel', 'name'],
            },
        ),
    ]
