# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-25 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0018_program_series_youtube_dedicated"),
        ("youtube", "0008_youtubebroadcastpreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("broadcast_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("ready", "ready"),
                            ("testing", "testing"),
                            ("live", "live"),
                            ("complete", "complete"),
                            ("error", "error"),
                        ],
                        default="created",
                        max_length=12,
                    ),
                ),
                ("checklist_state", models.JSONField(blank=True, default=dict)),
                ("manual", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="youtube.youtubebroadcastpreset",
                    ),
                ),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_broadcast",
                        to="scheduling.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_broadcast",
                "ordering": ["-created_at"],
            },
        ),
    ]
