# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_notification"),
        ("medialib", "0003_backfill_screening_approved"),
        ("playout", "0005_playoutevent_ad_break_item"),
        ("scheduling", "0003_series_program_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "screening_status",
                    models.CharField(
                        choices=[
                            ("pending", "未考査"),
                            ("approved", "考査OK"),
                            ("rejected", "考査NG"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "advertiser",
            },
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "agency",
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "industry",
            },
        ),
        migrations.CreateModel(
            name="AdContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("time", "タイム(番組提供)"), ("spot", "スポット")], max_length=8
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("active", "active"),
                            ("fulfilled", "fulfilled"),
                            ("cancelled", "cancelled"),
                            ("expired", "expired"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="sales.advertiser",
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="sales.agency",
                    ),
                ),
            ],
            options={
                "db_table": "ad_contract",
            },
        ),
        migrations.CreateModel(
            name="CmAdvertiserLink",
            fields=[
                (
                    "cm_asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="advertiser_link",
                        serialize=False,
                        to="medialib.cmcreative",
                    ),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cm_links",
                        to="sales.advertiser",
                    ),
                ),
            ],
            options={
                "db_table": "cm_advertiser_link",
            },
        ),
        migrations.AddField(
            model_name="advertiser",
            name="industry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advertisers",
                to="sales.industry",
            ),
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[("A", "A"), ("SB", "特B"), ("B", "B"), ("C", "C")], max_length=2
                    ),
                ),
                ("unit_seconds", models.IntegerField()),
                ("price", models.IntegerField()),
                ("effective_from", models.DateField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.channel",
                    ),
                ),
            ],
            options={
                "db_table": "rate_card",
            },
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("seconds_per_episode", models.IntegerField()),
                ("monthly_fee", models.IntegerField()),
                ("credit_text", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships",
                        to="sales.adcontract",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="scheduling.series",
                    ),
                ),
            ],
            options={
                "db_table": "sponsorship",
            },
        ),
        migrations.CreateModel(
            name="Airing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bundle_seq", models.IntegerField(default=0)),
                ("program_title", models.TextField(blank=True, null=True)),
                ("duration_ms", models.BigIntegerField()),
                ("aired_at", models.DateTimeField()),
                ("aired_at_estimated", models.BooleanField(default=False)),
                ("billed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.channel",
                    ),
                ),
                (
                    "cm_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="medialib.cmcreative",
                    ),
                ),
                (
                    "playout_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airings",
                        to="playout.playoutevent",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="scheduling.program",
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="airings",
                        to="sales.sponsorship",
                    ),
                ),
            ],
            options={
                "db_table": "airing",
            },
        ),
        migrations.CreateModel(
            name="SponsorshipMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seq", models.IntegerField()),
                (
                    "cm_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="medialib.cmcreative",
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="sales.sponsorship",
                    ),
                ),
            ],
            options={
                "db_table": "sponsorship_material",
            },
        ),
        migrations.CreateModel(
            name="SpotOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("target_count", models.IntegerField()),
                ("unit_seconds", models.IntegerField()),
                ("unit_price", models.IntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.channel",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spot_orders",
                        to="sales.adcontract",
                    ),
                ),
            ],
            options={
                "db_table": "spot_order",
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match_kind",
                    models.CharField(
                        choices=[
                            ("sponsorship", "提供"),
                            ("program", "指定番組"),
                            ("band", "線引き"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad_break_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement",
                        to="scheduling.adbreakitem",
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="sales.sponsorship",
                    ),
                ),
                (
                    "spot_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="sales.spotorder",
                    ),
                ),
            ],
            options={
                "db_table": "placement",
            },
        ),
        migrations.CreateModel(
            name="MakeGood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("replaced", "replaced"),
                            ("credited", "credited"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "missed_playout_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="playout.playoutevent",
                    ),
                ),
                (
                    "replacement_airing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.airing",
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="make_goods",
                        to="sales.sponsorship",
                    ),
                ),
                (
                    "spot_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="make_goods",
                        to="sales.spotorder",
                    ),
                ),
            ],
            options={
                "db_table": "make_good",
            },
        ),
        migrations.AddField(
            model_name="airing",
            name="spot_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="airings",
                to="sales.spotorder",
            ),
        ),
        migrations.CreateModel(
            name="SpotOrderBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dow_mask", models.IntegerField(default=127)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "spot_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="sales.spotorder",
                    ),
                ),
            ],
            options={
                "db_table": "spot_order_band",
            },
        ),
        migrations.CreateModel(
            name="SpotOrderMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seq", models.IntegerField()),
                (
                    "cm_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="medialib.cmcreative",
                    ),
                ),
                (
                    "spot_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="sales.spotorder",
                    ),
                ),
            ],
            options={
                "db_table": "spot_order_material",
            },
        ),
        migrations.CreateModel(
            name="SpotOrderProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="scheduling.series",
                    ),
                ),
                (
                    "spot_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="sales.spotorder",
                    ),
                ),
            ],
            options={
                "db_table": "spot_order_program",
            },
        ),
        migrations.CreateModel(
            name="TimeBandRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dow", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "rank",
                    models.CharField(
                        choices=[("A", "A"), ("SB", "特B"), ("B", "B"), ("C", "C")], max_length=2
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.channel",
                    ),
                ),
            ],
            options={
                "db_table": "time_band_rank",
            },
        ),
        migrations.AddConstraint(
            model_name="adcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="chk_contract_period",
            ),
        ),
        migrations.AddIndex(
            model_name="cmadvertiserlink",
            index=models.Index(fields=["advertiser"], name="idx_cm_adv_link_advertiser"),
        ),
        migrations.AddConstraint(
            model_name="ratecard",
            constraint=models.UniqueConstraint(
                fields=("channel", "rank", "unit_seconds", "effective_from"), name="uq_rate_card"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsorship",
            constraint=models.UniqueConstraint(
                fields=("contract", "series"), name="uq_sponsorship"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsorshipmaterial",
            constraint=models.UniqueConstraint(
                fields=("sponsorship", "seq"), name="uq_sponsorship_material"
            ),
        ),
        migrations.AddConstraint(
            model_name="spotorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="chk_spot_period",
            ),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["spot_order"], name="idx_placement_order"),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["sponsorship"], name="idx_placement_sponsorship"),
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sponsorship__isnull", True), ("spot_order__isnull", False)),
                    models.Q(("sponsorship__isnull", False), ("spot_order__isnull", True)),
                    _connector="OR",
                ),
                name="chk_placement_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("match_kind", "sponsorship"), ("sponsorship__isnull", False)),
                    models.Q(
                        models.Q(("match_kind", "sponsorship"), _negated=True),
                        ("sponsorship__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_placement_match",
            ),
        ),
        migrations.AddIndex(
            model_name="makegood",
            index=models.Index(
                condition=models.Q(("status", "open")), fields=["status"], name="idx_mg_open"
            ),
        ),
        migrations.AddConstraint(
            model_name="makegood",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sponsorship__isnull", True), ("spot_order__isnull", False)),
                    models.Q(("sponsorship__isnull", False), ("spot_order__isnull", True)),
                    _connector="OR",
                ),
                name="chk_mg_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="makegood",
            constraint=models.UniqueConstraint(
                condition=models.Q(("missed_playout_event__isnull", False)),
                fields=("missed_playout_event",),
                name="uq_mg_missed_event",
            ),
        ),
        migrations.AddIndex(
            model_name="airing",
            index=models.Index(fields=["spot_order", "aired_at"], name="idx_airing_order_period"),
        ),
        migrations.AddIndex(
            model_name="airing",
            index=models.Index(
                fields=["sponsorship", "aired_at"], name="idx_airing_sponsorship_period"
            ),
        ),
        migrations.AddIndex(
            model_name="airing",
            index=models.Index(
                condition=models.Q(("billed", False)),
                fields=["aired_at"],
                name="idx_airing_unbilled",
            ),
        ),
        migrations.AddConstraint(
            model_name="airing",
            constraint=models.UniqueConstraint(
                fields=("playout_event", "bundle_seq"), name="uq_airing_event_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="airing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sponsorship__isnull", False), ("spot_order__isnull", False), _negated=True
                ),
                name="chk_airing_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="spotorderband",
            constraint=models.CheckConstraint(
                condition=models.Q(("dow_mask__gte", 1), ("dow_mask__lte", 127)),
                name="chk_band_dow_mask",
            ),
        ),
        migrations.AddConstraint(
            model_name="spotorderband",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))), name="chk_band_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="spotordermaterial",
            constraint=models.UniqueConstraint(
                fields=("spot_order", "seq"), name="uq_spot_order_material"
            ),
        ),
        migrations.AddConstraint(
            model_name="spotorderprogram",
            constraint=models.UniqueConstraint(
                fields=("spot_order", "series"), name="uq_spot_order_program"
            ),
        ),
        migrations.AddConstraint(
            model_name="timebandrank",
            constraint=models.CheckConstraint(
                condition=models.Q(("dow__gte", 0), ("dow__lte", 6)), name="chk_tbr_dow"
            ),
        ),
        migrations.AddConstraint(
            model_name="timebandrank",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))), name="chk_tbr_time"
            ),
        ),
    ]
