# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-09 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('medialib', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('action', models.CharField(choices=[('play_asset', 'play_asset'), ('play_cm', 'play_cm'), ('play_cm_bundle', 'play_cm_bundle'), ('cut_live', 'cut_live'), ('play_filler', 'play_filler'), ('play_slate', 'play_slate'), ('yt_transition', 'yt_transition')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('executing', 'executing'), ('done', 'done'), ('skipped', 'skipped'), ('failed', 'failed')], default='scheduled', max_length=12)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.asset')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playout_events', to='core.channel')),
                ('cm_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.cmbundle')),
                ('live_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.livesource')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.program')),
                ('youtube_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youtube.youtubeslot')),
            ],
            options={
                'db_table': 'playout_event',
                'indexes': [models.Index(fields=['channel', 'scheduled_at'], name='idx_pe_ch_sched'), models.Index(condition=models.Q(('status', 'scheduled')), fields=['status'], name='idx_pe_scheduled')],
            },
        ),
    ]
