# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
        ('playout', '0003_playoutstatus_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent_status', serialize=False, to='core.channel')),
                ('last_heartbeat_at', models.DateTimeField()),
                ('last_received_seq', models.BigIntegerField(default=0)),
                ('queue_depth', models.IntegerField(default=0)),
                ('caspar_health', models.CharField(blank=True, max_length=20, null=True)),
                ('feed_state', models.CharField(blank=True, max_length=10, null=True)),
                ('slate_active', models.BooleanField(default=False)),
                ('auto_return', models.BooleanField(default=True)),
                ('auto_return_suspended', models.BooleanField(default=False)),
                ('offline_notified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_status',
            },
        ),
        migrations.AlterField(
            model_name='playoutevent',
            name='action',
            field=models.CharField(choices=[('play_asset', 'play_asset'), ('play_cm', 'play_cm'), ('play_cm_bundle', 'play_cm_bundle'), ('cut_live', 'cut_live'), ('play_filler', 'play_filler'), ('play_slate', 'play_slate'), ('yt_transition', 'yt_transition'), ('clear_slate', 'clear_slate')], max_length=20),
        ),
    ]
