# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playout', '0004_agentstatus_alter_playoutevent_action'),
        ('scheduling', '0002_adbreak_grid_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoutevent',
            name='ad_break_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.adbreakitem'),
        ),
    ]
