# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playout', '0005_playoutevent_ad_break_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatus',
            name='layers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
