# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playout", "0008_alter_playoutevent_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentstatus",
            name="slate_stuck_notified",
            field=models.BooleanField(default=False),
        ),
    ]
