# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playout', '0009_agentstatus_slate_stuck_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoutevent',
            name='action',
            field=models.CharField(choices=[('play_asset', 'play_asset'), ('play_cm', 'play_cm'), ('play_cm_bundle', 'play_cm_bundle'), ('cut_live', 'cut_live'), ('play_filler', 'play_filler'), ('play_slate', 'play_slate'), ('yt_transition', 'yt_transition'), ('clear_slate', 'clear_slate'), ('overlay_op', 'overlay_op'), ('play_vt', 'play_vt'), ('yt_mirror_filler', 'yt_mirror_filler'), ('yt_mirror_route', 'yt_mirror_route')], max_length=20),
        ),
    ]
