# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-14 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0004_deliveryinvitation'),
        ('scheduling', '0008_episode_program_episode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('incurred_on', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='delivery.delivery')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_costs', to='scheduling.series')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='delivery.productioncompany')),
            ],
            options={
                'db_table': 'delivery_cost',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField()),
                ('paid_at', models.DateField()),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.deliverycost')),
            ],
            options={
                'db_table': 'procurement_payment',
            },
        ),
        migrations.CreateModel(
            name='ProgramBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='scheduling.series')),
            ],
            options={
                'db_table': 'program_budget',
            },
        ),
        migrations.AddIndex(
            model_name='deliverycost',
            index=models.Index(fields=['series', 'incurred_on'], name='idx_delivery_cost_series'),
        ),
        migrations.AddConstraint(
            model_name='programbudget',
            constraint=models.UniqueConstraint(fields=('series', 'fiscal_year'), name='uq_program_budget'),
        ),
    ]
