# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medialib', '0001_initial'),
        ('scheduling', '0002_adbreak_grid_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'production_company',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='scheduling.program')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='delivery.productioncompany')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='DeliveryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('broadcast', '本編(放送)'), ('distribution', '配信'), ('promo', '番宣'), ('sales', '番販'), ('archive', '保管')], max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('uploading', 'uploading'), ('uploaded', 'uploaded'), ('qc_processing', 'qc_processing'), ('qc_failed', 'qc_failed'), ('qc_passed', 'qc_passed'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=16)),
                ('intended_kind', models.CharField(blank=True, choices=[('program', '番組'), ('cm', 'CM'), ('filler', 'フィラー'), ('bumper', 'バンパー'), ('slate', 'スレート')], max_length=16, null=True)),
                ('r2_key', models.CharField(blank=True, max_length=500, null=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('upload_state', models.CharField(choices=[('pending', 'pending'), ('uploading', 'uploading'), ('complete', 'complete'), ('aborted', 'aborted')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medialib.asset')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='delivery.delivery')),
            ],
            options={
                'db_table': 'delivery_file',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('external', '外部制作会社'), ('internal_qc', '社内QC'), ('internal_admin', '社内管理者')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='delivery.productioncompany')),
            ],
            options={
                'db_table': 'delivery_account',
            },
        ),
        migrations.CreateModel(
            name='QcReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_result', models.JSONField(default=dict)),
                ('auto_verdict', models.CharField(choices=[('ok', 'ok'), ('warn', 'warn'), ('ng', 'ng')], max_length=4)),
                ('loudness_i', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('loudness_lra', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('true_peak', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('human_verdict', models.CharField(blank=True, choices=[('ok', 'ok'), ('warn', 'warn'), ('ng', 'ng')], max_length=4, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_reports', to='delivery.deliveryfile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qc_report',
            },
        ),
        migrations.CreateModel(
            name='SheetExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cue_sheet', 'キューシート'), ('record_sheet', '記録表')], max_length=16)),
                ('r2_key', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_exports', to='scheduling.program')),
            ],
            options={
                'db_table': 'sheet_export',
            },
        ),
        migrations.AddIndex(
            model_name='deliveryfile',
            index=models.Index(fields=['delivery'], name='idx_delivery_file_delivery'),
        ),
        migrations.AddIndex(
            model_name='deliveryfile',
            index=models.Index(fields=['status'], name='idx_delivery_file_status'),
        ),
        migrations.AddConstraint(
            model_name='deliveryfile',
            constraint=models.UniqueConstraint(fields=('delivery', 'purpose', 'version'), name='uq_delivery_file_version'),
        ),
        migrations.AddConstraint(
            model_name='deliveryaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', False), ('role', 'external')), models.Q(models.Q(('role', 'external'), _negated=True), ('company__isnull', True)), _connector='OR'), name='chk_role_company'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['company'], name='idx_delivery_company'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['program'], name='idx_delivery_program'),
        ),
        migrations.AddIndex(
            model_name='qcreport',
            index=models.Index(fields=['delivery_file'], name='idx_qc_report_file'),
        ),
    ]
