# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-14 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_channel_slate_asset'),
        ('delivery', '0001_initial'),
        ('sales', '0001_initial'),
        ('scheduling', '0008_episode_program_episode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.channel'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='scheduling.episode'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.sponsorship'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='spot_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.spotorder'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='target_kind',
            field=models.CharField(choices=[('series_episode', '週間編成番組の特定回'), ('oneoff', '単発番組'), ('cm', 'CM')], default='oneoff', max_length=16),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['episode'], name='idx_delivery_episode'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['target_kind'], name='idx_delivery_target_kind'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('sponsorship__isnull', False), ('spot_order__isnull', False), _negated=True), name='chk_delivery_cm_one'),
        ),
    ]
