# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfile',
            name='qc_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
