# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryfile_qc_started_at'),
        # procurement 0002 は SeparateDatabaseAndState で DeliveryCost の delivery/vendor FK を
        # IntegerField 化する。state から FK が消えるため autodetector はこの順序を張れないが、
        # migration 実行時は procurement 0002 の履歴 state (FK を含む) を描画するため
        # delivery.Delivery がその時点で必要。よって drop はこの後でなければならない。
        ('procurement', '0002_deliverycost_decouple_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfile',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryaccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='deliveryaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deliveryfile',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='delivery_file',
        ),
        migrations.RemoveField(
            model_name='deliveryinvitation',
            name='accepted_user',
        ),
        migrations.RemoveField(
            model_name='deliveryinvitation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='deliveryinvitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='sheetexport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sheetexport',
            name='program',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryAccount',
        ),
        migrations.DeleteModel(
            name='DeliveryFile',
        ),
        migrations.DeleteModel(
            name='ProductionCompany',
        ),
        migrations.DeleteModel(
            name='DeliveryInvitation',
        ),
        migrations.DeleteModel(
            name='QcReport',
        ),
        migrations.DeleteModel(
            name='SheetExport',
        ),
    ]
