# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from icstv.v1 import playout_pb2 as icstv_dot_v1_dot_playout__pb2


class PlayoutAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeEvents = channel.unary_stream(
                '/icstv.v1.PlayoutAgent/SubscribeEvents',
                request_serializer=icstv_dot_v1_dot_playout__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=icstv_dot_v1_dot_playout__pb2.SubscribeEventsResponse.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/icstv.v1.PlayoutAgent/ReportResult',
                request_serializer=icstv_dot_v1_dot_playout__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=icstv_dot_v1_dot_playout__pb2.ReportResultResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/icstv.v1.PlayoutAgent/Heartbeat',
                request_serializer=icstv_dot_v1_dot_playout__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=icstv_dot_v1_dot_playout__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReportInterrupt = channel.unary_unary(
                '/icstv.v1.PlayoutAgent/ReportInterrupt',
                request_serializer=icstv_dot_v1_dot_playout__pb2.ReportInterruptRequest.SerializeToString,
                response_deserializer=icstv_dot_v1_dot_playout__pb2.ReportInterruptResponse.FromString,
                _registered_method=True)
        self.RequestRecordingUpload = channel.unary_unary(
                '/icstv.v1.PlayoutAgent/RequestRecordingUpload',
                request_serializer=icstv_dot_v1_dot_playout__pb2.RequestRecordingUploadRequest.SerializeToString,
                response_deserializer=icstv_dot_v1_dot_playout__pb2.RequestRecordingUploadResponse.FromString,
                _registered_method=True)


class PlayoutAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeEvents(self, request, context):
        """agent が起動時に開く長期ストリーム。再接続時は last_known_seq で resume。
        Response は wrapper にして将来 heartbeat/system message を混在できる余地を残す。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """as-run 実績の返送 (store-and-forward)。同一 idempotency_key は最新で上書き。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """死活・queue 深さ・CasparCG ヘルス。30s 周期。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportInterrupt(self, request, context):
        """agent 起点の割り込み報告 (feed 断→自動退避 / 自動復帰 / フラップ停止)。
        事前生成イベントが無いため ReportResult とは別 RPC。interrupt_key で冪等 (#7 決定 O4)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRecordingUpload(self, request, context):
        """生放送録画 (record_live) 完了後、agent が録画クリップの R2 アップロード先を要求する。
        送出ノードは R2 へ直接アクセスできないため、都度 presigned PUT URL を server が発行する
        (scheduling.live_recording が ingest/live_recording/ 配下を後日 scan して取り込む)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayoutAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=icstv_dot_v1_dot_playout__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=icstv_dot_v1_dot_playout__pb2.SubscribeEventsResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=icstv_dot_v1_dot_playout__pb2.ReportResultRequest.FromString,
                    response_serializer=icstv_dot_v1_dot_playout__pb2.ReportResultResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=icstv_dot_v1_dot_playout__pb2.HeartbeatRequest.FromString,
                    response_serializer=icstv_dot_v1_dot_playout__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReportInterrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportInterrupt,
                    request_deserializer=icstv_dot_v1_dot_playout__pb2.ReportInterruptRequest.FromString,
                    response_serializer=icstv_dot_v1_dot_playout__pb2.ReportInterruptResponse.SerializeToString,
            ),
            'RequestRecordingUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRecordingUpload,
                    request_deserializer=icstv_dot_v1_dot_playout__pb2.RequestRecordingUploadRequest.FromString,
                    response_serializer=icstv_dot_v1_dot_playout__pb2.RequestRecordingUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'icstv.v1.PlayoutAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('icstv.v1.PlayoutAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlayoutAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/icstv.v1.PlayoutAgent/SubscribeEvents',
            icstv_dot_v1_dot_playout__pb2.SubscribeEventsRequest.SerializeToString,
            icstv_dot_v1_dot_playout__pb2.SubscribeEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icstv.v1.PlayoutAgent/ReportResult',
            icstv_dot_v1_dot_playout__pb2.ReportResultRequest.SerializeToString,
            icstv_dot_v1_dot_playout__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icstv.v1.PlayoutAgent/Heartbeat',
            icstv_dot_v1_dot_playout__pb2.HeartbeatRequest.SerializeToString,
            icstv_dot_v1_dot_playout__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportInterrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icstv.v1.PlayoutAgent/ReportInterrupt',
            icstv_dot_v1_dot_playout__pb2.ReportInterruptRequest.SerializeToString,
            icstv_dot_v1_dot_playout__pb2.ReportInterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRecordingUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icstv.v1.PlayoutAgent/RequestRecordingUpload',
            icstv_dot_v1_dot_playout__pb2.RequestRecordingUploadRequest.SerializeToString,
            icstv_dot_v1_dot_playout__pb2.RequestRecordingUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
