# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('interval', models.CharField(choices=[('month', '月額'), ('year', '年額')], default='month', max_length=5)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('feat_ad_free', models.BooleanField(default=False, verbose_name='広告非表示')),
                ('feat_hd', models.BooleanField(default=False, verbose_name='高画質')),
                ('feat_comment_perk', models.BooleanField(default=False, verbose_name='コメント特典')),
                ('feat_exclusive', models.BooleanField(default=False, verbose_name='会員限定コンテンツ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_plan',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='MemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', '有効'), ('trialing', 'トライアル'), ('past_due', '支払遅延'), ('canceled', '解約済'), ('incomplete', '未完了'), ('unpaid', '未払い')], default='incomplete', max_length=12)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='members.member')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'member_subscription',
                'indexes': [models.Index(fields=['stripe_subscription_id'], name='idx_sub_stripe_sub')],
            },
        ),
    ]
