# SPDX-FileCopyrightText: 2026 アイシーエス
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.1.15 on 2026-06-18 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0011_program_cast_series_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='曲名')),
                ('artist', models.CharField(blank=True, default='', max_length=300, verbose_name='実演家')),
                ('composer', models.CharField(blank=True, default='', max_length=300, verbose_name='作曲')),
                ('lyricist', models.CharField(blank=True, default='', max_length=300, verbose_name='作詞')),
                ('isrc', models.CharField(blank=True, default='', max_length=32, verbose_name='ISRC')),
                ('society', models.CharField(choices=[('jasrac', 'JASRAC'), ('nextone', 'NexTone'), ('other', 'その他団体'), ('none', '管理外/自社')], default='none', max_length=8, verbose_name='管理団体')),
                ('work_code', models.CharField(blank=True, default='', max_length=64, verbose_name='作品コード')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rights_song',
                'indexes': [models.Index(fields=['title'], name='idx_song_title')],
            },
        ),
        migrations.CreateModel(
            name='DistributionRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=200, verbose_name='権利元')),
                ('contract_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='契約ID')),
                ('allow_linear', models.BooleanField(default=True, verbose_name='リニア配信')),
                ('allow_vod', models.BooleanField(default=True, verbose_name='VOD配信')),
                ('allow_youtube', models.BooleanField(default=True, verbose_name='YouTube配信')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='配信可能 開始')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='配信可能 終了')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rights', to='scheduling.program')),
            ],
            options={
                'db_table': 'rights_distribution',
                'indexes': [models.Index(fields=['program'], name='idx_distright_program')],
            },
        ),
        migrations.CreateModel(
            name='SongUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_kind', models.CharField(choices=[('theme', '主題歌'), ('insert', '挿入歌'), ('bgm', 'BGM'), ('cm', 'CM')], default='bgm', max_length=8, verbose_name='用途')),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='使用秒数')),
                ('seq', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='備考')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_usages', to='scheduling.program')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='rights.song')),
            ],
            options={
                'db_table': 'rights_song_usage',
                'ordering': ['program', 'seq', 'id'],
                'indexes': [models.Index(fields=['program', 'seq'], name='idx_usage_program')],
            },
        ),
    ]
